# To run it, do:
#   $ docker-compose pull && docker-compose up -d
#
# To upgrade, do:
#   $ docker-compose pull && docker-compose stop && docker-compose rm -f && docker-compose up -d
#
# To check the logs, do:
#   $ docker-compose logs -f
#

version: '2'

services:
  nextcloud:
    image: jefferyb/nextcloud
    restart: always
    container_name: nextcloud-server
    links:
      - nextcloud-database:mysql
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/nextcloud/nextcloud-data/data:/var/www/html/data
      - /opt/nextcloud/nextcloud-data/config:/var/www/html/config
      # ENABLE_SSL = true --- certs location
      - /opt/letsencrypt/letsencrypt-data/etc/letsencrypt/live/nextcloud.example.com/cert.pem:/etc/ssl/certs/ssl-cert-snakeoil.pem:ro
      - /opt/letsencrypt/letsencrypt-data/etc/letsencrypt/live/nextcloud.example.com/privkey.pem:/etc/ssl/private/ssl-cert-snakeoil.key:ro
    environment:
      - "TZ=America/Chicago"
      - "WEB_INSTALL=false"
      - "DATABASE_ROOT_PASSWORD=Chang3m3t0an0th3r"
      - "EXTERNAL_URL=nextcloud.example.com"
      - "ENABLE_SSL=true"

  nextcloud-database:
    image: mysql/mysql-server
    container_name: nextcloud-database
    restart: always
    volumes:
      - /opt/nextcloud/nextcloud-mysql-data:/var/lib/mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=Chang3m3t0an0th3r"
      - "TZ=America/Chicago"
